import { Button, Stack } from 'react-bootstrap';
import { useLotterytStore } from 'src/stores/lotterytStore';
import Form from 'react-bootstrap/Form';
import { FormEventHandler } from 'react';
import { useRouter } from 'next/router';

function QuickStart() {
  const router = useRouter();
  const setStraws = useLotterytStore((state) => state.setStraws);
  const setAwards = useLotterytStore((state) => state.setAwards);
  const start = useLotterytStore((state) => state.start);
  const lock = useLotterytStore((state) => state.lock);

  const onSubmit: FormEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const data = Object.fromEntries(formData.entries());
    const personCount = +data.personCount.toString();
    const awardCount = +data.awardCount.toString();

    const straws = Array.from(Array(personCount)).map((_e, i) => ({
      no: i + 1,
      name: 'QS-' + (i + 1),
      group: 'QuickStart',
    }));
    setStraws(straws);
    setAwards([
      {
        name: 'The Lucky One',
        description: 'Generated by Quick Start',
        quota: awardCount,
        order: 1,
        pic: '',
      },
    ]);
    router.push('/').then(() => start());
  };

  return (
    <>
      <Stack gap={2} className="col-md-4 col-12 mx-auto">
        <div>
          <h2>Quick Start</h2>
        </div>
        <div className="py-2">
          <Form onSubmit={onSubmit}>
            <Form.Group className="mb-3" controlId="personCount">
              <Form.Label>抽獎人數</Form.Label>
              <Form.Control
                name="personCount"
                type="number"
                placeholder="抽獎人數"
                defaultValue={3}
                min={2}
              />
            </Form.Group>
            <Form.Group className="mb-3" controlId="awardCount">
              <Form.Label>中獎人數</Form.Label>
              <Form.Control
                name="awardCount"
                type="number"
                placeholder="獎項數量"
                defaultValue={1}
                min={1}
              />
            </Form.Group>
            <Button
              className="col-12  my-4"
              variant="primary"
              type="submit"
              disabled={lock}
            >
              LET&apos;S GO!
            </Button>
          </Form>
        </div>
      </Stack>
    </>
  );
}

export default QuickStart;
