import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { Button, Stack } from 'react-bootstrap';
import { useLotterytStore } from 'src/stores/lotterytStore';
import Card from 'react-bootstrap/Card';
import Table from 'react-bootstrap/Table';

const Home: NextPage = () => {
  const straws = useLotterytStore((state) => state.straws);
  const awards = useLotterytStore((state) => state.awards);
  const winners = useLotterytStore((state) => state.winners);

  const awardsToDraw = useLotterytStore((state) => state.awardsToDraw);
  const currentAward = awardsToDraw && awardsToDraw[0];

  const start = useLotterytStore((state) => state.start);
  const draw = useLotterytStore((state) => state.draw);
  const reset = useLotterytStore((state) => state.reset);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Go to <Link href="/edit">Edit!</Link>
        </h1>
        <Stack gap={3} className="col-md-5 mx-auto">
          <Button
            onClick={() => start()}
            disabled={straws.length === 0 || awards.length === 0}
          >
            LET&apos;S GO!
          </Button>
          <Button variant="danger" onClick={() => reset()}>
            Reset
          </Button>
          {currentAward && (
            <Card style={{ width: '24rem' }} className="text-center mx-auto">
              <Card.Img variant="top" src="/gift.png" />
              <Card.Body>
                <Card.Title>{currentAward.name}</Card.Title>
                <Card.Text>{currentAward.description}</Card.Text>
                <Card.Text>
                  This award will have {currentAward.count} winner(s)
                </Card.Text>
                <Button variant="primary" onClick={() => draw()}>
                  WINNER GOES TO!
                </Button>
              </Card.Body>
            </Card>
          )}
          <div>
            <Table striped bordered hover>
              <thead>
                <tr>
                  <th>Award Name</th>
                  <th>Winner(s)</th>
                </tr>
              </thead>
              <tbody>
                {winners.map((val) => (
                  <tr key={val.awardName}>
                    <td>{val.awardName}</td>
                    <td>{val.straws.map((st) => st.name).join(', ')}</td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </div>
        </Stack>
      </main>
    </div>
  );
};

export default Home;
